version: "3.8"
# documentation
# https://docs.docker.com/compose/
# versions reference
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  backend:
    image: "luuductrung1234/fullstack-demo:latest"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: _demo-db-url_
      SPRING_DATASOURCE_USERNAME: _demo-db-username_
      SPRING_DATASOURCE_PASSWORD: _demo-db-password_
    ports:
      - "80:8080"

#  mariadb:
#    image: mariadb
#    container_name: demo-mariadb
#    restart: "always"
#    environment:
#      - MARIADB_ROOT_PASSWORD=P@ssword1
#    ports:
#      - 3306:3306
#    volumes:
#      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql