version: "3.8"
# documentation
# https://docs.docker.com/compose/
# versions reference
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  backend:
    image: "luuductrung1234/fullstack-demo:latest"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: _demo-db-url_
      SPRING_DATASOURCE_USERNAME: _demo-db-username_
      SPRING_DATASOURCE_PASSWORD: _demo-db-password_
    ports:
      - "80:8080"

#  mysqldb:
#    platform: linux/x86_64
#    image: mysql
#    container_name: demo-mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: "no"
#    environment:
#      - MYSQL_ROOT_PASSWORD=P@ssword1
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql