name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  # Database
  DB_DB: demodb
  DB_USER: sa
  DB_PASSWORD: P@ssword1
  # Java
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysqldb:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_DB }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Verify Code Changed
        id: verify-changed-code
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            **/pom.xml
            src
            src/**
            src/**/*.sql
            src/**/*.yml
            src/**/*.java
            src/**/*.js
            src/**/*.html
            src/**/*.css
            src/**/*.json

      - name: List All Changed Files
        if: steps.verify-changed-code.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.verify-changed-code.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Maven Clean Package
        if: steps.verify-changed-code.outputs.any_changed == 'true'
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend -l build-output.log

      - name: Upload build output file
        uses: actions/upload-artifact@v3
        with:
          name: build-output-file
          path: build-output.log