name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DB_VERSION: 10.8
  DB_DB: demodb
  DB_USER: sa
  DB_PASSWORD: P@ssword1
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MARIADB_DATABASE: ${{ env.DB_DB }}
          MARIADB_USER: ${{ env.DB_USER }}
          MARIADB_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend