name: CICD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  # Database
  DB_DB: demodb
  DB_USER: sa
  DB_PASSWORD: P@ssword1
  # Java
  JAVA_VERSION: 11
  # Pipeline
  REPO_NAME: AmazingEnergy/full-stack-demo-01
  PIPELINE_COMPOSE_FILE: pipeline/docker-compose.yml
  DOCKER_IMAGE: luuductrung1234/fullstack-demo
  # DockerHub
  DOCKER_HUB_USERNAME: luuductrung1234
  DOCKER_HUB_REPO_URL: https://hub.docker.com/repository/docker/luuductrung1234/fullstack-demo
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-southeast-1
  EB_ENVIRONMENT_NAME: Fullstackdemo-env
  EB_APPLICATION_NAME: fullstack-demo
  EB_DEPLOYMENT_PACKAGE: pipeline/docker-compose.yml
  EB_DEPLOYED_URL: http://fullstackdemo-env.eba-37nkzcf2.ap-southeast-1.elasticbeanstalk.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MARIADB_DATABASE: ${{ env.DB_DB }}
          MARIADB_USER: ${{ env.DB_USER }}
          MARIADB_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Maven Clean Package and Push to Dockerhub
        run: |
          ./mvnw --no-transfer-progress clean package \
            -P build-frontend \
            -P push-to-registry \
              -Dimage.tag=${{steps.build-number.outputs.BUILD_NUMBER}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':white_check_mark: pushed ${{env.DOCKER_IMAGE}}:${{steps.build-number.outputs.BUILD_NUMBER}} to docker hub... ${{env.DOCKER_HUB_REPO_URL}}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "==========================================\n"
          echo -e "Before Changes \n"
          echo -e "==========================================\n"
          echo -e "Current ${{env.PIPELINE_COMPOSE_FILE}}\n$(cat ${{env.PIPELINE_COMPOSE_FILE}})"
          sed -i -E 's_(${{env.DOCKER_IMAGE}}:)([^"]*)_\1'${BUILD_NUMBER}'_' ${{env.PIPELINE_COMPOSE_FILE}}
          echo -e "\n==========================================\n"
          echo -e "After Changes\n"
          echo -e "==========================================\n"
          echo -e "Current ${{env.PIPELINE_COMPOSE_FILE}}\n$(cat ${{env.PIPELINE_COMPOSE_FILE}})"
          echo -e "\n==========================================\n"
          echo -e "Push Changes\n"
          echo -e "==========================================\n"
          git config user.name luuductrung1234
          git config user.email luuductrung1234@gmail.com
          git remote set-url --push origin https://your_username:${{secrets.PAT}}@github.com/${{env.REPO_NAME}}
          git add ${{env.PIPELINE_COMPOSE_FILE}}
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push

      - name: Upload modified docker-compose file
        uses: actions/upload-artifact@v3
        with:
          name: modified-docker-compose
          path: ${{env.PIPELINE_COMPOSE_FILE}}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':elasticbeanstalk: :aws: Deployment started... :grimacing: :crossed_fingers:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed via github actions ${{ github.sha }}
          wait_for_deployment: 60

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':cry: :x: something went wrong! please check!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: :arrow_right: ${{env.EB_DEPLOYED_URL}}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()